### ISSUE TITLE
question: const skip is unused 

### ISSUE THREAD

**Issue by adamdecaf** [bracesdev/errtrace#68]
In `GetCaller()` the `skip` constant isn't actually used in runtime.Callers, which seems like an oversight. The const is nice to document going back up the call trace.

```go
	const skip = 1 + // frame for Callers
		1 + // frame for GetCaller
		1 // frame for our caller, which should be errtrace.Wrap

	var callers [1]uintptr
	n := runtime.Callers(3, callers[:]) // skip getcallerpc + caller
```

https://github.com/bracesdev/errtrace/blob/main/internal/pc/pc_safe.go#L9-L14

**Comment by abhinav** [comment]
Oops, this was indeed an oversight.
Thanks for catching!
